blank_issues_enabled: false
contact_links:
  - name: Multron Community Discussions
    url: https://github.com/orgs/Multron-Community/discussions
    about: Sorular, genel fikir alışverişi ve mimari tartışmalar için lütfen burayı kullanın.